/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    kullanicilar: KullanicilarAuthOperations;
  };
  blocks: {};
  collections: {
    ilanlar: Ilanlar;
    mahalleler: Mahalleler;
    'ilgi-noktalari': IlgiNoktalari;
    talepler: Talepler;
    'danisman-basvurulari': DanismanBasvurulari;
    degerlemeler: Degerlemeler;
    gozlemler: Gozlemler;
    'rayic-degerler': RayicDegerler;
    'vergi-parametreleri': VergiParametreleri;
    sayfalar: Sayfalar;
    medya: Medya;
    'altbilgi-baglantilari': AltbilgiBaglantilari;
    kullanicilar: Kullanicilar;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    ilanlar: IlanlarSelect<false> | IlanlarSelect<true>;
    mahalleler: MahallelerSelect<false> | MahallelerSelect<true>;
    'ilgi-noktalari': IlgiNoktalariSelect<false> | IlgiNoktalariSelect<true>;
    talepler: TaleplerSelect<false> | TaleplerSelect<true>;
    'danisman-basvurulari': DanismanBasvurulariSelect<false> | DanismanBasvurulariSelect<true>;
    degerlemeler: DegerlemelerSelect<false> | DegerlemelerSelect<true>;
    gozlemler: GozlemlerSelect<false> | GozlemlerSelect<true>;
    'rayic-degerler': RayicDegerlerSelect<false> | RayicDegerlerSelect<true>;
    'vergi-parametreleri': VergiParametreleriSelect<false> | VergiParametreleriSelect<true>;
    sayfalar: SayfalarSelect<false> | SayfalarSelect<true>;
    medya: MedyaSelect<false> | MedyaSelect<true>;
    'altbilgi-baglantilari': AltbilgiBaglantilariSelect<false> | AltbilgiBaglantilariSelect<true>;
    kullanicilar: KullanicilarSelect<false> | KullanicilarSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'kurumsal-bilgiler': KurumsalBilgiler;
    hakkimizda: Hakkimizda;
    'hero-slider': HeroSlider;
    'marka-gorunum': MarkaGorunum;
    'site-bolumleri': SiteBolumleri;
    'menu-duzeni': MenuDuzeni;
    'portfoy-bolumleri': PortfoyBolumleri;
    'danisman-ol': DanismanOl;
    'degerleme-ayarlari': DegerlemeAyarlari;
    'endeks-ayarlari': EndeksAyarlari;
    'bakim-durumu': BakimDurumu;
    'google-places-kullanimi': GooglePlacesKullanimi;
  };
  globalsSelect: {
    'kurumsal-bilgiler': KurumsalBilgilerSelect<false> | KurumsalBilgilerSelect<true>;
    hakkimizda: HakkimizdaSelect<false> | HakkimizdaSelect<true>;
    'hero-slider': HeroSliderSelect<false> | HeroSliderSelect<true>;
    'marka-gorunum': MarkaGorunumSelect<false> | MarkaGorunumSelect<true>;
    'site-bolumleri': SiteBolumleriSelect<false> | SiteBolumleriSelect<true>;
    'menu-duzeni': MenuDuzeniSelect<false> | MenuDuzeniSelect<true>;
    'portfoy-bolumleri': PortfoyBolumleriSelect<false> | PortfoyBolumleriSelect<true>;
    'danisman-ol': DanismanOlSelect<false> | DanismanOlSelect<true>;
    'degerleme-ayarlari': DegerlemeAyarlariSelect<false> | DegerlemeAyarlariSelect<true>;
    'endeks-ayarlari': EndeksAyarlariSelect<false> | EndeksAyarlariSelect<true>;
    'bakim-durumu': BakimDurumuSelect<false> | BakimDurumuSelect<true>;
    'google-places-kullanimi': GooglePlacesKullanimiSelect<false> | GooglePlacesKullanimiSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Kullanicilar;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface KullanicilarAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Portföydeki taşınmazlar. Bir ilan yayına alınabilmesi için EİDS yetkisinin geçerli olması zorunludur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ilanlar".
 */
export interface Ilanlar {
  id: number;
  /**
   * Danışmansanız: ilanı hazırlayıp "Onay bekliyor" seçin — yönetici EİDS bilgilerini doğrulayıp yayınlar. Vazgeçerseniz "Taslak"a geri çekebilirsiniz. Yayın kararı yöneticide, çünkü yetki belgesi işletme sahibinin adına. ⚠️ "Yayında" veya "Rezerve" için EİDS sekmesindeki tüm koşullar ayrıca sağlanmalıdır.
   */
  durum: 'taslak' | 'onay_bekliyor' | 'yayinda' | 'rezerve' | 'satildi' | 'yetki_bitti';
  /**
   * Sayfanın adres satırındaki adı. Boş bırakırsan başlıktan otomatik üretilir. Yayına girdikten sonra değiştirmek eski adresi 404 yapar.
   */
  slug: string;
  danisman?: (number | null) | Kullanicilar;
  oneCikan?: boolean | null;
  /**
   * İşaretliyse ilanın adresi, fotoğrafları ve detayları herkese gösterilmez; yalnızca mahalle, kategori, m² aralığı ve fiyat bandı görünür. (Faz 2B modülü)
   */
  gizliPortfoy?: boolean | null;
  /**
   * Örn: "Muhittin Mahallesi'nde 3+1, 135 m², asansörlü". Rakam ve mahalle adı geçsin — arama motorunda fark eder.
   */
  baslik: string;
  tip: 'satilik' | 'kiralik';
  kategori: 'konut' | 'isyeri' | 'arsa' | 'depo' | 'fabrika';
  /**
   * Liste kartlarında ve paylaşımlarda görünen 1-2 cümle. Boş bırakılırsa açıklamanın başı kullanılır.
   */
  ozet?: string | null;
  aciklama?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. En fazla 70 karakter.
   */
  seoBaslik?: string | null;
  /**
   * Google sonuçlarında başlığın altında görünen metin. En fazla 170 karakter.
   */
  seoAciklama?: string | null;
  /**
   * WhatsApp ve sosyal medyada paylaşıldığında görünecek görsel. Önerilen: 1200×630 piksel.
   */
  seoGorsel?: (number | null) | Medya;
  il: string;
  ilce: string;
  mahalle: number | Mahalleler;
  /**
   * Yalnızca yönetim panelinde görünür, siteye çıkmaz. Randevu ve dosya takibi için.
   */
  adres?: string | null;
  /**
   * Haritadaki konum. Gizli portföyde tam nokta yerine mahalle merkezi gösterilir.
   *
   * @minItems 2
   * @maxItems 2
   */
  konum?: [number, number] | null;
  /**
   * Tapu bilgisi. Yayın için zorunludur (EİDS).
   */
  ada?: string | null;
  /**
   * Tapu bilgisi. Yayın için zorunludur (EİDS).
   */
  parsel?: string | null;
  tapuDurumu?: ('kat_mulkiyeti' | 'kat_irtifaki' | 'arsa_tapulu' | 'hisseli' | 'mustakil') | null;
  /**
   * Mülk sahibi e-Devlet → "EİDS Taşınmaz İlanı Yetkilendirme İşlemleri" üzerinden işletmeyi yetkilendirir. Yalnızca "Yetkili" durumunda ilan yayınlanabilir.
   */
  eidsDurum?: ('yetkili' | 'suresi_doldu' | 'yetkisiz' | 'tapusuz' | 'yabanci_malik') | null;
  /**
   * İlan sayfasında "Doğrulanmış İlan" rozetiyle birlikte ziyaretçiye gösterilir.
   */
  tasinmazNo?: string | null;
  eidsYetkiBaslangic?: string | null;
  /**
   * Yetki en az 3 ay verilir. Süre dolduğunda ilan otomatik olarak yayından kaldırılır.
   */
  eidsYetkiBitis?: string | null;
  /**
   * Kiralık ilanlarda aylık kira bedelidir.
   */
  fiyat?: number | null;
  paraBirimi?: ('TRY' | 'USD' | 'EUR') | null;
  /**
   * Satılık ilanlarda yatırım göstergelerini bu alan besler. Bilmiyorsan BOŞ BIRAK — tahmini rakam yazma, göstergeler boş durumda kalsın.
   */
  tahminiKira?: number | null;
  aidat?: number | null;
  pazarlikPayi?: boolean | null;
  /**
   * fiyat ÷ (kira × 12)
   */
  kiraCarpani?: number | null;
  brutGetiri?: number | null;
  amortismanYili?: number | null;
  brutM2?: number | null;
  netM2?: number | null;
  odaSayisi?: ('1+0' | '1+1' | '2+1' | '3+1' | '4+1' | '5+1') | null;
  banyoSayisi?: number | null;
  /**
   * Taşınmazın hangi yöne baktığı. Köşe daireler için birden fazla seçin. Bilmiyorsanız BOŞ BIRAKIN — tahmin edilmez, güneş haritasında boş durum gösterilir.
   */
  cepheYonu?: ('kuzey' | 'kuzeydogu' | 'dogu' | 'guneydogu' | 'guney' | 'guneybati' | 'bati' | 'kuzeybati')[] | null;
  /**
   * Örn: 3, Zemin, Bahçe katı
   */
  bulunduguKat?: string | null;
  toplamKat?: number | null;
  binaYasi?: number | null;
  isinma?: ('dogalgaz_kombi' | 'merkezi' | 'merkezi_pay_olcer' | 'yerden_isitma' | 'klima' | 'soba' | 'yok') | null;
  kullanimDurumu?: ('bos' | 'kiracili' | 'mulk_sahibi') | null;
  esyali?: boolean | null;
  krediyeUygun?: boolean | null;
  asansor?: boolean | null;
  /**
   * Örn: "Otoparklı", "Site içerisinde", "Güneybatı cephe"
   */
  ozellikler?:
    | {
        metin: string;
        id?: string | null;
      }[]
    | null;
  /**
   * İlk fotoğraf kapak olarak kullanılır.
   */
  gorseller?:
    | {
        gorsel: number | Medya;
        id?: string | null;
      }[]
    | null;
  katPlani?: (number | null) | Medya;
  /**
   * Bunny Stream video kimliği. Boşsa video bölümü hiç gösterilmez.
   */
  droneVideoId?: string | null;
  /**
   * Tam adres (https://...). Boşsa tur bölümü gösterilmez.
   */
  sanalTurUrl?: string | null;
  yetkilendirmeSozlesmesi?: (number | null) | Medya;
  gostermeBelgesi?: (number | null) | Medya;
  belgeNotu?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kullanicilar".
 */
export interface Kullanicilar {
  id: number;
  adSoyad: string;
  /**
   * Yönetici her şeye erişir. Danışman günlük portföy ve talep işini yapar; ayarlara, hukuki metinlere, vergi oranlarına dokunamaz ve kayıt silemez. Bu alanı yalnızca yönetici değiştirebilir.
   */
  rol?: ('yonetici' | 'danisman') | null;
  telefon?: string | null;
  fotograf?: (number | null) | Medya;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'kullanicilar';
}
/**
 * Site görselleri. Video yüklenmez — videolar CDN üzerinden yayınlanır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medya".
 */
export interface Medya {
  id: number;
  /**
   * Görselde ne olduğunu bir cümleyle yaz. Ekran okuyucu kullananlar ve görsel yüklenmediğinde herkes bunu görür. Örn: "Muhittin Mahallesi'nde 3+1 dairenin salonu".
   */
  alt: string;
  /**
   * Görsel size ait değilse kaynağını yazın. Boş bırakılırsa kendi çekimimiz sayılır.
   */
  kaynak?: string | null;
  /**
   * Boyut bütçesi buna göre değerlendirilir. Hero görseli sayfanın en büyük öğesidir ve açılış hızını doğrudan belirler.
   */
  kullanim?: ('belirsiz' | 'hero' | 'kart') | null;
  tahminiKartBayt?: number | null;
  tahminiMobilBayt?: number | null;
  tahminiMasaustuBayt?: number | null;
  bulanikVeri?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    kucuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    orta?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    buyuk?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    paylasim?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Mahalle mini-portalları. Her mahalle sayfası ayrı bir SEO varlığıdır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mahalleler".
 */
export interface Mahalleler {
  id: number;
  /**
   * İçerik metni hazır olmadan yayına alma. 800 kelimeden kısa sayfalar arama motorunda "zayıf içerik" sayılır ve tüm siteyi aşağı çeker.
   */
  yayinda?: boolean | null;
  /**
   * Sayfanın adres satırındaki adı. Boş bırakırsan başlıktan otomatik üretilir. Yayına girdikten sonra değiştirmek eski adresi 404 yapar.
   */
  slug: string;
  /**
   * İşaretliyse bu kaydın rakamları henüz girilmemiştir. Arayüzde boş durum gösterilir, uydurma sayı yazılmaz.
   */
  veriEksik?: boolean | null;
  /**
   * Küçük sayı önce gösterilir.
   */
  siraNo?: number | null;
  /**
   * "Mahallesi" eki olmadan. Örn: Muhittin
   */
  ad: string;
  /**
   * Kırsal mahalleler (eski köyler) sitede ayrıca işaretlenir. Emin değilseniz boş bırakın — boş alan rozet göstermez.
   */
  yerlesimTuru?: ('merkez' | 'kirsal') | null;
  /**
   * Mahalle listesinde ve kartlarda görünen 1-2 cümle.
   */
  ozet?: string | null;
  /**
   * Mahalleyi tanımlayan 3-6 madde. Örn: "OSB'ye 10 dakika", "Yoğun öğrenci nüfusu"
   */
  oneCikanOzellikler?:
    | {
        metin: string;
        id?: string | null;
      }[]
    | null;
  kapakGorseli?: (number | null) | Medya;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. En fazla 70 karakter.
   */
  seoBaslik?: string | null;
  /**
   * Google sonuçlarında başlığın altında görünen metin. En fazla 170 karakter.
   */
  seoAciklama?: string | null;
  /**
   * WhatsApp ve sosyal medyada paylaşıldığında görünecek görsel. Önerilen: 1200×630 piksel.
   */
  seoGorsel?: (number | null) | Medya;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Google'da "Sorular ve cevaplar" bloğu olarak görünebilir (FAQPage yapılandırılmış verisi).
   */
  sikSorulanlar?:
    | {
        soru: string;
        cevap: string;
        id?: string | null;
      }[]
    | null;
  ortalamaM2Satis?: number | null;
  ortalamaKira?: number | null;
  /**
   * Kaç yıllık kira, satış fiyatına eşit.
   */
  kiraCarpani?: number | null;
  degisim12Ay?: number | null;
  /**
   * Resmî kaynaktan (TÜİK/belediye) teyit edilmeden girme.
   */
  nufus?: number | null;
  /**
   * Bu rakamlar kaç gözleme dayanıyor? Sitede her rakamın yanında gösterilir. n bilinmiyorsa rakamlar da yayınlanmamalıdır.
   */
  gozlemSayisi?: number | null;
  verilerinTarihi?: string | null;
  /**
   * Örn: "Kendi gözlem kayıtlarımız", "TÜİK". Sitede kaynak açıkça belirtilir.
   */
  veriKaynagi?: string | null;
  /**
   * Haritanın odaklanacağı nokta.
   *
   * @minItems 2
   * @maxItems 2
   */
  merkez?: [number, number] | null;
  /**
   * OpenStreetMap sınır içe aktarma ekranından tek tıkla doldurulabilir. Elle çizmek isterseniz geojson.io üzerinde çizip çıktıyı buraya yapıştırın. Boşsa haritada sınır çizgisi gösterilmez, sadece merkez noktası kullanılır.
   */
  sinir?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * İçe aktarma bunu kendisi yazar. OpenStreetMap kaynaklı sınırlar sitede "© OpenStreetMap katkıcıları" atfıyla gösterilir (ODbL lisansı gereği).
   */
  sinirKaynagi?: ('elle' | 'osm') | null;
  /**
   * Örn. "relation/123456". Yeniden içe aktarmada aynı sınırı bulmak için.
   */
  sinirOsmKimlik?: string | null;
  /**
   * Sınırı ya da merkez noktasını elle değiştirdiğinizde otomatik işaretlenir ve yeniden içe aktarma onu EZMEZ. İşareti kaldırırsanız sınır tekrar OpenStreetMap'ten güncellenir.
   */
  sinirElleDuzenlendi?: boolean | null;
  /**
   * Bunny Stream video kimliği. Boşsa hero bölümü görsele düşer.
   */
  droneVideoId?: string | null;
  /**
   * Video yüklenene kadar gösterilir. Sayfanın en büyük görseli budur — LCP'yi belirler.
   */
  droneVideoPosteri?: (number | null) | Medya;
  sanalTurUrl?: string | null;
  yatirimSkoru?: {
    /**
     * Bileşenlerden otomatik hesaplanır. Yeterli bileşen verisi yoksa boş kalır.
     */
    toplam?: number | null;
    /**
     * Skorun yanında "[tarih] itibarıyla" olarak gösterilir.
     */
    hesaplanmaTarihi?: string | null;
    /**
     * Ağırlık %25. Çorlu ortalamasına göre göreli performans.
     */
    fiyatTrendi?: number | null;
    /**
     * Ağırlık %20. DÜŞÜK çarpan YÜKSEK puan alır.
     */
    kiraCarpaniPuani?: number | null;
    /**
     * Ağırlık %15.
     */
    sanayiYakinligi?: number | null;
    /**
     * Ağırlık %15.
     */
    ulasim?: number | null;
    /**
     * Ağırlık %15.
     */
    sosyalDonati?: number | null;
    /**
     * Ağırlık %10. ÇOK yeni arz DÜŞÜK puan alır.
     */
    arzBaskisi?: number | null;
  };
  eslestirmeProfili?: {
    /**
     * Araç kullanmayan biri için otobüs/dolmuş erişimi ve hat sıklığı. 100 = araçsız rahatça yaşanır.
     */
    topluTasima?: number | null;
    /**
     * Okul öncesi, ilkokul ve ortaokullara yürüme mesafesi. 100 = çocuk okula yürüyerek gider.
     */
    okulErisimi?: number | null;
    /**
     * Trafik, gürültü ve yoğunluk. 100 = çok sakin, 0 = ana arter üzerinde. Bu bir kalite yargısı DEĞİL: kimi sakinlik ister, kimi hareket.
     */
    sessizlik?: number | null;
    /**
     * Çorlu merkezine ve çarşıya yakınlık. 100 = merkezde. Sakinlikle genellikle ters çalışır; ikisini birlikte düşünün.
     */
    merkezeYakinlik?: number | null;
    /**
     * Bu puanları neye göre verdiğinizi yazın. Bir ziyaretçi "neden bu mahalle önerildi?" diye sorduğunda cevabınız hazır olsun.
     */
    profilNotu?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Haritadaki katmanlar ve mesafe hesapları bu kayıtlardan beslenir. Konum girilmemiş kayıtlar haritada gösterilmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ilgi-noktalari".
 */
export interface IlgiNoktalari {
  id: number;
  ad: string;
  tip:
    | 'okul'
    | 'universite'
    | 'hastane'
    | 'eczane'
    | 'market'
    | 'avm'
    | 'park'
    | 'oyun_alani'
    | 'sanayi'
    | 'durak'
    | 'istasyon'
    | 'havalimani'
    | 'resmi';
  /**
   * Haritadan seçin veya koordinat girin. Mesafe hesapları bu noktayı kullanır.
   *
   * @minItems 2
   * @maxItems 2
   */
  konum: [number, number];
  /**
   * İçe aktarmada otomatik belirlenir: nokta hangi mahalle poligonunun içindeyse o. Elle değiştirdiğinizde kayıt "elle düzeltildi" işaretlenir ve bir daha ezilmez.
   */
  mahalle?: (number | null) | Mahalleler;
  /**
   * İçe aktarma bu noktayı hiçbir mahalle sınırının içinde bulamadı ve en yakın mahalle merkezine atadı. Doğru mahalleyi biliyorsanız elle düzeltin.
   */
  mahalleYaklasik?: boolean | null;
  /**
   * Şehir hastanesi, OSB, tren istasyonu gibi bölgenin değerini belirleyen noktalar. Mahalle sayfasında ayrıca vurgulanır.
   */
  onemli?: boolean | null;
  detay?: string | null;
  /**
   * İçe aktarma bunu kendisi yazar. OpenStreetMap kaynaklı kayıtlar sitede "© OpenStreetMap katkıcıları" atfıyla gösterilir (ODbL lisansı gereği). "Google Places" yalnızca elle girilen kayıtlar için bir köken beyanıdır — Google içeriği hiçbir zaman otomatik olarak kaydedilmez.
   */
  kaynak: 'elle' | 'osm' | 'google';
  /**
   * Google Places eşleştirme ekranından doldurulur. Yalnızca kimlik saklanır; çalışma saati ve işletme adı gösterileceği anda Google’dan çekilir, kaydedilmez (lisans gereği). Boşsa bu nokta için Google katmanı çalışmaz.
   */
  googlePlaceId?: string | null;
  /**
   * Örn. "node/123456". Yeniden içe aktarmada aynı kaydı bulmak için kullanılır.
   */
  osmKimlik?: string | null;
  /**
   * Bu kaydı panelden düzenlediğinizde otomatik işaretlenir ve yeniden içe aktarma onu EZMEZ. İşareti kaldırırsanız kayıt tekrar OSM'den güncellenir.
   */
  elleDuzenlendi?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Siteden gelen talepler. Kişisel veri içerir — dışarı aktarırken KVKK yükümlülüklerini gözetin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talepler".
 */
export interface Talepler {
  id: number;
  durum: 'yeni' | 'arandi' | 'randevu' | 'teklif' | 'kazanildi' | 'kaybedildi';
  /**
   * Otomatik hesaplanır (0-100). Talepleri SIRALAMAK içindir, elemek için değil — en kısa mesajı yazan kişi en hazır müşteri olabilir. Bileşenler: telefon, e-posta, mesaj ayrıntısı, bütçe, hedef belirginliği, talep tipi.
   */
  skor?: number | null;
  sonTemas?: string | null;
  adSoyad: string;
  tip: 'alici' | 'satici' | 'kiraci' | 'ticari' | 'degerleme' | 'genel';
  telefon?: string | null;
  eposta?: string | null;
  mesaj?: string | null;
  ilgiliIlan?: (number | null) | Ilanlar;
  ilgiliMahalle?: (number | null) | Mahalleler;
  butceMin?: number | null;
  butceMax?: number | null;
  kaynak?: ('organik' | 'dogrudan' | 'whatsapp' | 'instagram' | 'google_ads' | 'tavsiye' | 'diger') | null;
  gonderildigiSayfa?: string | null;
  kvkkOnay: boolean;
  kvkkOnayTarihi?: string | null;
  /**
   * Bu tarihten sonra kayıt otomatik silinir. KVKK: veri, amaç için gerekli süreden fazla saklanamaz.
   */
  saklamaBitis?: string | null;
  /**
   * Ayrı bir onaydır. İşaretli değilse bu kişiye bülten/kampanya gönderilemez.
   */
  pazarlamaOnayi?: boolean | null;
  notlar?:
    | {
        tarih?: string | null;
        metin: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Ekibe katılmak isteyenlerin başvuruları. Müşteri taleplerinden ayrı tutulur — farklı veri kategorisi, farklı saklama süresi.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danisman-basvurulari".
 */
export interface DanismanBasvurulari {
  id: number;
  durum?: ('yeni' | 'gorusuldu' | 'olumlu' | 'olumsuz') | null;
  ad: string;
  telefon: string;
  email: string;
  deneyim: 'yok' | '1_3' | '3_arti';
  /**
   * Taşınmaz Ticareti / Emlak Danışmanı mesleki yeterlilik belgesi.
   */
  mykBelgesi?: boolean | null;
  mesaj?: string | null;
  /**
   * ⚠️ Yalnızca panel kullanıcıları görür. Başvurucuya gösterilmez.
   */
  notlar?: string | null;
  /**
   * Onay olmadan kayıt oluşturulamaz.
   */
  kvkkOnay: boolean;
  kvkkOnayTarihi?: string | null;
  /**
   * Bu tarihten sonra bakım görevi kaydı siler.
   */
  saklamaBitis?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Siteden yapılan değerleme talepleri. İletişim bilgisi olmayan kayıtlar da değerlidir: hangi mahallede ne tür taşınmaz sorgulandığını gösterir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "degerlemeler".
 */
export interface Degerlemeler {
  id: number;
  durum?: ('yeni' | 'incelendi' | 'arandi' | 'randevu' | 'portfoye_alindi' | 'kapandi') | null;
  /**
   * İşaretsiz kayıtlar anonimdir; yalnızca talep sinyali taşır.
   */
  iletisimVar?: boolean | null;
  ozet?: string | null;
  mahalle?: (number | null) | Mahalleler;
  brutM2?: number | null;
  odaSayisi?: string | null;
  kat?: ('bodrum' | 'zemin' | 'ara' | 'yuksek' | 'en_ust') | null;
  binaYasi?: number | null;
  yapiDurumu?: ('sifir' | 'iyi' | 'ortalama' | 'tadilat') | null;
  adresNotu?: string | null;
  tahminiAlt?: number | null;
  tahminiUst?: number | null;
  guvenDuzeyi?: string | null;
  /**
   * İşlem gerçekleştiyse buraya yazın. Bu, modelin ne kadar isabetli olduğunu ölçmenin tek yolu — zamanla katsayıları buna göre düzeltin.
   */
  gerceklesenDeger?: number | null;
  notlar?: string | null;
  adSoyad?: string | null;
  telefon?: string | null;
  eposta?: string | null;
  kvkkOnay?: boolean | null;
  kvkkOnayTarihi?: string | null;
  /**
   * Bu tarihten sonra kişisel veriler otomatik silinir.
   */
  saklamaBitis?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Endeksin ham verisi. Tek tek kayıtlar asla yayınlanmaz — yalnızca toplulaştırılmış göstergeler yayınlanır. Haftalık hedef: 30 gözlem.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gozlemler".
 */
export interface Gozlemler {
  id: number;
  mahalle: number | Mahalleler;
  tip: 'satilik' | 'kiralik';
  odaTipi: '1+1' | '2+1' | '3+1' | '4+1';
  m2: number;
  /**
   * Kiralıkta aylık kira bedeli.
   */
  fiyat: number;
  /**
   * Otomatik hesaplanır. Beklediğinizden çok farklıysa m² veya fiyatı yanlış girmiş olabilirsiniz.
   */
  m2Fiyati?: number | null;
  gozlemTarihi: string;
  /**
   * ⚠️ İstenen fiyat ile gerçekleşen fiyat AYRI serilerde hesaplanır. Karıştırmak endeksi sistematik olarak şişirir.
   */
  kaynak: 'portal_ilan' | 'kendi_islem' | 'meslektas' | 'resmi';
  binaYasi?: number | null;
  kat?: string | null;
  /**
   * Geriye dönük girilen kayıtları "Düşük" işaretleyin. Grafikte kesikli çizgiyle gösterilir ve gerçek gözlemle karıştırılmaz.
   */
  guvenSeviyesi?: ('yuksek' | 'orta' | 'dusuk') | null;
  /**
   * Aykırı bir değer girdiyseniz sebebini yazın — altı ay sonra siz de hatırlamayacaksınız.
   */
  notlar?: string | null;
  /**
   * Endeks hesabı bu alanı kullanır (YYYY-AA).
   */
  ay?: string | null;
  ozet?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Emlak vergisine esas asgari değerler. ⚠️ Piyasa fiyatı DEĞİLDİR — piyasanın çoğu yerde altındadır. Kaynağı ve yılı sitede her gösterimde birlikte yayınlanır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rayic-degerler".
 */
export interface RayicDegerler {
  id: number;
  /**
   * Listede görünen ad; kaydettiğinizde otomatik üretilir.
   */
  ozet?: string | null;
  mahalle: number | Mahalleler;
  /**
   * Rayiç bedelin ait olduğu yıl. Her yıl yeniden değerleme oranıyla artar; yıl yazılmadan rakam anlamsızdır.
   */
  yil: number;
  /**
   * Belediye tabloları çoğu zaman sokak bazında gelir. Boş bırakılırsa değer mahallenin geneli için kabul edilir. ⚠️ Sokak bazlı ve mahalle geneli kayıtlar birlikte durabilir; site mahalle genelini kullanır.
   */
  sokak?: string | null;
  /**
   * Konut/bina için metrekare başına vergiye esas asgari değer.
   */
  metrekareRayicBedel?: number | null;
  /**
   * Arsa metrekaresi başına vergiye esas asgari değer.
   */
  arsaRayicBedel?: number | null;
  /**
   * Sitede rakamın yanında aynen gösterilir.
   */
  kaynak: 'belediye' | 'tkgm' | 'elle';
  /**
   * Tabloyu hangi tarihte aldığınız. "Veriler [tarih] itibarıyladır" ibaresi bundan üretilir.
   */
  guncellemeTarihi?: string | null;
  /**
   * Hangi belediye, hangi tablo, hangi sayfa. ⚠️ Kaynağı "elle" seçtiyseniz nereden aldığınızı buraya yazın — kaynağı yazılmayan rakam denetlenemez.
   */
  notlar?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Hesaplayıcıların kullandığı oran ve tutarlar. Bir parametre girilmemişse ilgili hesaplayıcı çalışmaz ve ziyaretçiye eksik olanı söyler — yanlış rakam üretmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vergi-parametreleri".
 */
export interface VergiParametreleri {
  id: number;
  /**
   * Hangi oran/tutar olduğunu seçin. Liste kod tarafında tanımlıdır.
   */
  anahtar:
    | 'tapu_harci_orani_alici'
    | 'doner_sermaye_ucreti'
    | 'dask_tahmini_prim'
    | 'ekspertiz_ucreti'
    | 'emlak_komisyon_orani'
    | 'komisyon_kdv_orani'
    | 'kira_geliri_istisna_tutari'
    | 'goturu_gider_orani'
    | 'gelir_vergisi_dilimleri'
    | 'deger_artis_istisna_tutari'
    | 'deger_artis_muafiyet_yili';
  /**
   * ORAN ise ondalık girin: %2 için 0,02 — %20 için 0,2. TUTAR ise TL olarak girin. Dilim türü parametrede bu alan boş kalır.
   */
  deger?: number | null;
  /**
   * Artan oranlı tarife. Her dilim için ÜST SINIR ve ORAN girin. Son dilimin üst sınırını BOŞ bırakın ("ve üzeri" anlamına gelir). Sıralama önemli değil, sistem kendisi sıralar.
   */
  dilimler?:
    | {
        /**
         * En üst dilimde boş bırakın.
         */
        ustSinir?: number | null;
        /**
         * %15 için 0,15
         */
        oran: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Bu değer hangi yıl için geçerli? Örn: 2026
   */
  gecerlilikYili: number;
  /**
   * Hesaplayıcı sayfalarında "veriler [tarih] itibarıyladır" ibaresinde gösterilir.
   */
  guncellemeTarihi: string;
  /**
   * Bu değeri nereden aldınız? Örn: "Gelir İdaresi Başkanlığı 2026 tebliği". Bir gazeteci veya müşteri sorduğunda cevabınız net olsun.
   */
  kaynak?: string | null;
  aciklama?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Kurumsal ve hukuki metin sayfaları.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar".
 */
export interface Sayfalar {
  id: number;
  yayinda?: boolean | null;
  /**
   * Sayfanın adres satırındaki adı. Boş bırakırsan başlıktan otomatik üretilir. Yayına girdikten sonra değiştirmek eski adresi 404 yapar.
   */
  slug: string;
  /**
   * İşaretliyse sayfanın üstünde son güncelleme tarihi gösterilir ve arama motoruna öne çıkarılmaması bildirilir.
   */
  hukukiMetin?: boolean | null;
  baslik: string;
  ozet?: string | null;
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Boş bırakılırsa sayfa başlığı kullanılır. En fazla 70 karakter.
   */
  seoBaslik?: string | null;
  /**
   * Google sonuçlarında başlığın altında görünen metin. En fazla 170 karakter.
   */
  seoAciklama?: string | null;
  /**
   * WhatsApp ve sosyal medyada paylaşıldığında görünecek görsel. Önerilen: 1200×630 piksel.
   */
  seoGorsel?: (number | null) | Medya;
  updatedAt: string;
  createdAt: string;
}
/**
 * Altbilgideki dört sütunun içeriği. Sıra numarası küçük olan üstte görünür.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "altbilgi-baglantilari".
 */
export interface AltbilgiBaglantilari {
  id: number;
  sutun: 'kurumsal' | 'faydali' | 'hukuksal' | 'iletisim';
  siraNo?: number | null;
  baslik: string;
  /**
   * Site içi bağlantı için "/mahalleler" gibi yol; dış bağlantı için tam adres ("https://…"). Dış bağlantılarda güvenlik öznitelikleri otomatik eklenir.
   */
  url: string;
  /**
   * İşaretliyse aynı sekmede açılır. İşaretli değilse yeni sekmede açılır ve yanında dış bağlantı ikonu görünür.
   */
  dahiliMi?: boolean | null;
  aktif?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'ilanlar';
        value: number | Ilanlar;
      } | null)
    | ({
        relationTo: 'mahalleler';
        value: number | Mahalleler;
      } | null)
    | ({
        relationTo: 'ilgi-noktalari';
        value: number | IlgiNoktalari;
      } | null)
    | ({
        relationTo: 'talepler';
        value: number | Talepler;
      } | null)
    | ({
        relationTo: 'danisman-basvurulari';
        value: number | DanismanBasvurulari;
      } | null)
    | ({
        relationTo: 'degerlemeler';
        value: number | Degerlemeler;
      } | null)
    | ({
        relationTo: 'gozlemler';
        value: number | Gozlemler;
      } | null)
    | ({
        relationTo: 'rayic-degerler';
        value: number | RayicDegerler;
      } | null)
    | ({
        relationTo: 'vergi-parametreleri';
        value: number | VergiParametreleri;
      } | null)
    | ({
        relationTo: 'sayfalar';
        value: number | Sayfalar;
      } | null)
    | ({
        relationTo: 'medya';
        value: number | Medya;
      } | null)
    | ({
        relationTo: 'altbilgi-baglantilari';
        value: number | AltbilgiBaglantilari;
      } | null)
    | ({
        relationTo: 'kullanicilar';
        value: number | Kullanicilar;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'kullanicilar';
    value: number | Kullanicilar;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'kullanicilar';
    value: number | Kullanicilar;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ilanlar_select".
 */
export interface IlanlarSelect<T extends boolean = true> {
  durum?: T;
  slug?: T;
  danisman?: T;
  oneCikan?: T;
  gizliPortfoy?: T;
  baslik?: T;
  tip?: T;
  kategori?: T;
  ozet?: T;
  aciklama?: T;
  seoBaslik?: T;
  seoAciklama?: T;
  seoGorsel?: T;
  il?: T;
  ilce?: T;
  mahalle?: T;
  adres?: T;
  konum?: T;
  ada?: T;
  parsel?: T;
  tapuDurumu?: T;
  eidsDurum?: T;
  tasinmazNo?: T;
  eidsYetkiBaslangic?: T;
  eidsYetkiBitis?: T;
  fiyat?: T;
  paraBirimi?: T;
  tahminiKira?: T;
  aidat?: T;
  pazarlikPayi?: T;
  kiraCarpani?: T;
  brutGetiri?: T;
  amortismanYili?: T;
  brutM2?: T;
  netM2?: T;
  odaSayisi?: T;
  banyoSayisi?: T;
  cepheYonu?: T;
  bulunduguKat?: T;
  toplamKat?: T;
  binaYasi?: T;
  isinma?: T;
  kullanimDurumu?: T;
  esyali?: T;
  krediyeUygun?: T;
  asansor?: T;
  ozellikler?:
    | T
    | {
        metin?: T;
        id?: T;
      };
  gorseller?:
    | T
    | {
        gorsel?: T;
        id?: T;
      };
  katPlani?: T;
  droneVideoId?: T;
  sanalTurUrl?: T;
  yetkilendirmeSozlesmesi?: T;
  gostermeBelgesi?: T;
  belgeNotu?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "mahalleler_select".
 */
export interface MahallelerSelect<T extends boolean = true> {
  yayinda?: T;
  slug?: T;
  veriEksik?: T;
  siraNo?: T;
  ad?: T;
  yerlesimTuru?: T;
  ozet?: T;
  oneCikanOzellikler?:
    | T
    | {
        metin?: T;
        id?: T;
      };
  kapakGorseli?: T;
  seoBaslik?: T;
  seoAciklama?: T;
  seoGorsel?: T;
  icerik?: T;
  sikSorulanlar?:
    | T
    | {
        soru?: T;
        cevap?: T;
        id?: T;
      };
  ortalamaM2Satis?: T;
  ortalamaKira?: T;
  kiraCarpani?: T;
  degisim12Ay?: T;
  nufus?: T;
  gozlemSayisi?: T;
  verilerinTarihi?: T;
  veriKaynagi?: T;
  merkez?: T;
  sinir?: T;
  sinirKaynagi?: T;
  sinirOsmKimlik?: T;
  sinirElleDuzenlendi?: T;
  droneVideoId?: T;
  droneVideoPosteri?: T;
  sanalTurUrl?: T;
  yatirimSkoru?:
    | T
    | {
        toplam?: T;
        hesaplanmaTarihi?: T;
        fiyatTrendi?: T;
        kiraCarpaniPuani?: T;
        sanayiYakinligi?: T;
        ulasim?: T;
        sosyalDonati?: T;
        arzBaskisi?: T;
      };
  eslestirmeProfili?:
    | T
    | {
        topluTasima?: T;
        okulErisimi?: T;
        sessizlik?: T;
        merkezeYakinlik?: T;
        profilNotu?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ilgi-noktalari_select".
 */
export interface IlgiNoktalariSelect<T extends boolean = true> {
  ad?: T;
  tip?: T;
  konum?: T;
  mahalle?: T;
  mahalleYaklasik?: T;
  onemli?: T;
  detay?: T;
  kaynak?: T;
  googlePlaceId?: T;
  osmKimlik?: T;
  elleDuzenlendi?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talepler_select".
 */
export interface TaleplerSelect<T extends boolean = true> {
  durum?: T;
  skor?: T;
  sonTemas?: T;
  adSoyad?: T;
  tip?: T;
  telefon?: T;
  eposta?: T;
  mesaj?: T;
  ilgiliIlan?: T;
  ilgiliMahalle?: T;
  butceMin?: T;
  butceMax?: T;
  kaynak?: T;
  gonderildigiSayfa?: T;
  kvkkOnay?: T;
  kvkkOnayTarihi?: T;
  saklamaBitis?: T;
  pazarlamaOnayi?: T;
  notlar?:
    | T
    | {
        tarih?: T;
        metin?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danisman-basvurulari_select".
 */
export interface DanismanBasvurulariSelect<T extends boolean = true> {
  durum?: T;
  ad?: T;
  telefon?: T;
  email?: T;
  deneyim?: T;
  mykBelgesi?: T;
  mesaj?: T;
  notlar?: T;
  kvkkOnay?: T;
  kvkkOnayTarihi?: T;
  saklamaBitis?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "degerlemeler_select".
 */
export interface DegerlemelerSelect<T extends boolean = true> {
  durum?: T;
  iletisimVar?: T;
  ozet?: T;
  mahalle?: T;
  brutM2?: T;
  odaSayisi?: T;
  kat?: T;
  binaYasi?: T;
  yapiDurumu?: T;
  adresNotu?: T;
  tahminiAlt?: T;
  tahminiUst?: T;
  guvenDuzeyi?: T;
  gerceklesenDeger?: T;
  notlar?: T;
  adSoyad?: T;
  telefon?: T;
  eposta?: T;
  kvkkOnay?: T;
  kvkkOnayTarihi?: T;
  saklamaBitis?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gozlemler_select".
 */
export interface GozlemlerSelect<T extends boolean = true> {
  mahalle?: T;
  tip?: T;
  odaTipi?: T;
  m2?: T;
  fiyat?: T;
  m2Fiyati?: T;
  gozlemTarihi?: T;
  kaynak?: T;
  binaYasi?: T;
  kat?: T;
  guvenSeviyesi?: T;
  notlar?: T;
  ay?: T;
  ozet?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rayic-degerler_select".
 */
export interface RayicDegerlerSelect<T extends boolean = true> {
  ozet?: T;
  mahalle?: T;
  yil?: T;
  sokak?: T;
  metrekareRayicBedel?: T;
  arsaRayicBedel?: T;
  kaynak?: T;
  guncellemeTarihi?: T;
  notlar?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "vergi-parametreleri_select".
 */
export interface VergiParametreleriSelect<T extends boolean = true> {
  anahtar?: T;
  deger?: T;
  dilimler?:
    | T
    | {
        ustSinir?: T;
        oran?: T;
        id?: T;
      };
  gecerlilikYili?: T;
  guncellemeTarihi?: T;
  kaynak?: T;
  aciklama?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sayfalar_select".
 */
export interface SayfalarSelect<T extends boolean = true> {
  yayinda?: T;
  slug?: T;
  hukukiMetin?: T;
  baslik?: T;
  ozet?: T;
  icerik?: T;
  seoBaslik?: T;
  seoAciklama?: T;
  seoGorsel?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "medya_select".
 */
export interface MedyaSelect<T extends boolean = true> {
  alt?: T;
  kaynak?: T;
  kullanim?: T;
  tahminiKartBayt?: T;
  tahminiMobilBayt?: T;
  tahminiMasaustuBayt?: T;
  bulanikVeri?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        kucuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        orta?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        buyuk?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        paylasim?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "altbilgi-baglantilari_select".
 */
export interface AltbilgiBaglantilariSelect<T extends boolean = true> {
  sutun?: T;
  siraNo?: T;
  baslik?: T;
  url?: T;
  dahiliMi?: T;
  aktif?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kullanicilar_select".
 */
export interface KullanicilarSelect<T extends boolean = true> {
  adSoyad?: T;
  rol?: T;
  telefon?: T;
  fotograf?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Sitenin altbilgisinde ve /hakkimizda sayfasında görünen yasal ve iletişim bilgileri.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kurumsal-bilgiler".
 */
export interface KurumsalBilgiler {
  id: number;
  ticaretUnvani?: string | null;
  /**
   * Ticaret Bakanlığı tarafından verilen belge numarası. Sitenin altbilgisinde gösterilir.
   */
  yetkiBelgesiNo?: string | null;
  mersisNo?: string | null;
  vergiDairesi?: string | null;
  vergiNo?: string | null;
  sorumluDanismanBelgeNo?: string | null;
  adres?: string | null;
  telefon?: string | null;
  eposta?: string | null;
  /**
   * Uluslararası biçimde, yalnızca rakam. Örn: 905321234567. Boşsa sitedeki tüm WhatsApp butonları gizlenir.
   */
  whatsapp?: string | null;
  calismaSaatleri?: string | null;
  sosyalMedya?:
    | {
        platform: 'instagram' | 'youtube' | 'facebook' | 'linkedin' | 'x';
        adres: string;
        id?: string | null;
      }[]
    | null;
  /**
   * KVKK kapsamında veri sorumlusu sıfatını taşıyan kişi/işletme.
   */
  veriSorumlusu?: string | null;
  /**
   * Kayıt yükümlülüğünüz varsa. Yoksa boş bırakın.
   */
  verbisKayitNo?: string | null;
  /**
   * Silme/erişim taleplerinin gönderileceği adres.
   */
  kvkkBasvuruEpostasi?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sayfanın tanıtım metni ve görselleri. Yetki belgesi ve vergi bilgileri buraya YAZILMAZ — onlar Kurumsal Bilgiler’den otomatik geliyor.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hakkimizda".
 */
export interface Hakkimizda {
  id: number;
  /**
   * Başlığın hemen altındaki tek paragraf. Boşsa koddaki varsayılan cümle kullanılır.
   */
  girisMetni?: string | null;
  /**
   * Kimiz, nasıl çalışıyoruz, neye göre tavsiye veriyoruz. Biçimlendirme bilinçli olarak sınırlı: başlık, kalın, italik, liste, bağlantı.
   */
  icerik?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Dikey ya da kare çekim. Boş bırakılabilir — sayfa portresiz de düzgün çalışır.
   */
  portre?: (number | null) | Medya;
  /**
   * Fotoğrafın altında görünen kısa satır (ad, unvan).
   */
  portreAltMetni?: string | null;
  /**
   * Ofis, ekip, saha fotoğrafları. ⚠️ Bunlar sayfanın altında ızgarada gösteriliyor; her biri için medya kaydında "Kullanım: Kart" seçmek bütçe uyarısını doğru çalıştırır.
   */
  ekGorseller?:
    | {
        gorsel: number | Medya;
        /**
         * Görselin altında görünür. Boşsa yazı çıkmaz.
         */
        aciklama?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Ana sayfanın en üstündeki alan. Hiç slayt eklemezseniz mevcut metin hero’su görünmeye devam eder — site slayt olmadan da düzgün çalışır.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slider".
 */
export interface HeroSlider {
  id: number;
  /**
   * Sıra bu listedeki sıradır; sürükleyerek değiştirin. ⚠️ İLK slayt sayfanın LCP öğesidir: görselini "Hero" kullanımıyla yükleyin ve mobil bütçesini (80 kB) aşmayın.
   */
  slaytlar?:
    | {
        /**
         * Yatay, en az 1920 piksel geniş. Medya kaydında "Kullanım: Hero" seçerseniz panel size ziyaretçiye inecek gerçek boyutu ve bütçe durumunu gösterir.
         */
        gorsel: number | Medya;
        baslik: string;
        altBaslik?: string | null;
        /**
         * Boşsa buton hiç çıkmaz.
         */
        butonMetni?: string | null;
        /**
         * Örn. /degerleme veya /portfoy
         */
        butonLink?: string | null;
        metinHizasi?: ('sol' | 'orta') | null;
        /**
         * Görselin üstündeki koyu perde. ⚠️ Metnin okunabilmesi buna bağlı: açık renkli bir fotoğrafta düşük karartma başlığı okunmaz yapar.
         */
        overlayKoyulugu?: number | null;
        /**
         * Kapalı slayt sitede hiç görünmez ama kaydı silinmez.
         */
        aktif?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Varsayılan KAPALI. Açarsanız slaytlar kendiliğinden ilerler; duraklat düğmesi her zaman görünür ve "hareketi azalt" tercihi olan ziyaretçilerde geçiş hiç başlamaz.
   */
  otomatikGecis?: boolean | null;
  /**
   * Otomatik geçiş açıkken beklenecek süre. ⚠️ 4 saniyenin altına inilemiyor: okumaya vakit bırakmayan bir slider, olmayan bir slider’dan kötüdür.
   */
  gecisSuresi?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Logo, site adı ve renkler. Renk değişikliği kaydedildiği anda yayına girer — imajın yeniden derlenmesi gerekmez.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marka-gorunum".
 */
export interface MarkaGorunum {
  id: number;
  /**
   * Başlıkta, altbilgide ve sekme adında görünür. Boşsa "Aslıhan GYD" kullanılır.
   */
  siteAdi?: string | null;
  /**
   * Logonun yanında ve paylaşım kartlarında görünür.
   */
  slogan?: string | null;
  /**
   * SVG tercih edilir, PNG de kabul. ⚠️ Her sayfada yükleniyor — 50 kB üstü dosyalar için panelde uyarı çıkar.
   */
  logo?: (number | null) | Medya;
  /**
   * İsteğe bağlı. Boşsa koyu temada da ana logo kullanılır.
   */
  logoKoyu?: (number | null) | Medya;
  /**
   * KARE görsel, en az 512×512. Favicon, dokunma simgesi ve manifest ikonları bundan otomatik üretilir — ayrı ayrı yüklemenize gerek yok.
   */
  simgeKaynak?: (number | null) | Medya;
  /**
   * Sosyal medyada bağlantı paylaşıldığında görünen kart görseli. Önerilen 1200×630. Boşsa otomatik üretilen kart kullanılır.
   */
  ogGorseli?: (number | null) | Medya;
  /**
   * Sağ üstteki dolu buton. Boşsa "Değerleme isteyin" kullanılır. Kısa tutun — buton tek satırda kalmalı.
   */
  baslikEylemMetni?: string | null;
  /**
   * Boşsa /degerleme kullanılır.
   */
  baslikEylemAdresi?: string | null;
  acikTema: {
    /**
     * Sayfanın genel zemini.
     */
    zemin: string;
    /**
     * Vurgulanan bölümlerin zemini — ana zeminden ayrışmalı.
     */
    bolumZemin: string;
    /**
     * Gövde metninin rengi. Sitedeki en çok okunan renk.
     */
    metin: string;
    /**
     * Başlıklar ve bağlantılar. Metin olarak kullanıldığı için AA aranır.
     */
    vurgu: string;
    /**
     * Ana eylem butonlarının zemini.
     */
    butonZemin: string;
    /**
     * Buton üzerindeki yazı.
     */
    butonMetin: string;
    /**
     * Pudra tonu — hero ve yumuşak vurgu blokları. YALNIZCA ZEMİN: metin rengi olarak kullanılamaz.
     */
    yumusakZemin: string;
    /**
     * İnce ayraç çizgileri. YALNIZCA DEKORATİF: tek başına hiçbir bilgi taşımaz, metin rengi olarak kullanılamaz.
     */
    dekoratifCizgi: string;
    /**
     * Hero ve çağrı bantlarının koyu zemini.
     */
    koyuBantZemin: string;
    /**
     * Koyu bant üzerindeki yazı.
     */
    koyuBantMetin: string;
  };
  koyuTema: {
    /**
     * Sayfanın genel zemini.
     */
    zemin: string;
    /**
     * Vurgulanan bölümlerin zemini — ana zeminden ayrışmalı.
     */
    bolumZemin: string;
    /**
     * Gövde metninin rengi. Sitedeki en çok okunan renk.
     */
    metin: string;
    /**
     * Başlıklar ve bağlantılar. Metin olarak kullanıldığı için AA aranır.
     */
    vurgu: string;
    /**
     * Ana eylem butonlarının zemini.
     */
    butonZemin: string;
    /**
     * Buton üzerindeki yazı.
     */
    butonMetin: string;
    /**
     * Pudra tonu — hero ve yumuşak vurgu blokları. YALNIZCA ZEMİN: metin rengi olarak kullanılamaz.
     */
    yumusakZemin: string;
    /**
     * İnce ayraç çizgileri. YALNIZCA DEKORATİF: tek başına hiçbir bilgi taşımaz, metin rengi olarak kullanılamaz.
     */
    dekoratifCizgi: string;
    /**
     * Hero ve çağrı bantlarının koyu zemini.
     */
    koyuBantZemin: string;
    /**
     * Koyu bant üzerindeki yazı.
     */
    koyuBantMetin: string;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bir bölümü kapattığında ana sayfadan, altbilgiden ve arama motorundan aynı anda kalkar; adresine girilirse 404 döner. Verisi silinmez, geri açtığında yerinde olur.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-bolumleri".
 */
export interface SiteBolumleri {
  id: number;
  /**
   * Ekibe katılmak isteyen danışmanların başvuru sayfası.
   */
  danisman_ol?: boolean | null;
  /**
   * Tam ekran 3B Çorlu haritası. ⚠️ Altlık MapTiler’dan geliyor; anahtar ya da kota sorunu yaşarsanız sayfayı bozuk bırakmak yerine buradan kapatabilirsiniz.
   */
  harita?: boolean | null;
  /**
   * İş yeri, depo, fabrika ve arsa odaklı dikey sayfa.
   */
  ticari?: boolean | null;
  /**
   * Endeks sayfası. ⚠️ Kapalıyken de, açıkken de veri eşiği ayrıca kontrol edilir.
   */
  endeks?: boolean | null;
  /**
   * Değerleme, simülatör ve kira/satın alma raporlarının yazdırma sayfaları.
   */
  raporlar?: boolean | null;
  /**
   * İlan verilmeyen taşınmazların maskelenmiş listesi ve erişim talebi.
   */
  gizli_portfoy?: boolean | null;
  /**
   * Ziyaretçiye uygun mahalleyi öneren kısa test.
   */
  mahalle_testi?: boolean | null;
  /**
   * Çok yıllı getiri projeksiyonu hesaplayıcısı.
   */
  simulator?: boolean | null;
  /**
   * ⚠️ Portföy sayfasındaki "kendi cümlenizle arayın" kutusu. Ziyaretçinin yazdığı metin Anthropic'in (ABD) sunucularına gider — yurt dışına veri aktarımı. Aydınlatma metni avukattan gelmeden AÇMAYIN.
   */
  ai_arama?: boolean | null;
  /**
   * ⚠️ ÜCRETLİ. OpenStreetMap’in zayıf kaldığı yerde işletme adı ve çalışma saatlerini Google’dan tamamlar. Anahtar (GOOGLE_PLACES_API_KEY) tanımlı değilse açık olsa bile çalışmaz. Aylık çağrı sayısı Ayarlar → Google Places Kullanımı ekranında.
   */
  google_places?: boolean | null;
  /**
   * Mahalle medyanına göre fırsat ve risk sinyalleri.
   */
  bolge_radari?: boolean | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Üst menüdeki başlıkların sırası. Satırları sürükleyerek düzenleyin. Bir başlığı tamamen kaldırmak için Site Bölümleri’nden kapatın — buradan silmek onu yalnızca menünün sonuna atar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-duzeni".
 */
export interface MenuDuzeni {
  id: number;
  /**
   * Soldan sağa menü sırası. Kapalı bölümler bu listede dursa da sitede görünmez.
   */
  sira?:
    | {
        oge: 'portfoy' | 'mahalleler' | 'harita' | 'araclar' | 'endeks' | 'hakkimizda' | 'danisman_ol' | 'iletisim';
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Portföy sayfasındaki tema sıraları. Ölçüt kodda tanımlıdır; buradan başlığı, açıklamayı, kaç taşınmaz görüneceğini ve sırayı yönetirsin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfoy-bolumleri".
 */
export interface PortfoyBolumleri {
  id: number;
  /**
   * Sıralar buradaki düzende gösterilir. ⚠️ Bir taşınmaz yalnızca ilk girdiği sırada görünür — yukarıdaki sıra onu "kapar".
   */
  siralar?:
    | {
        /**
         * Hangi taşınmazların bu sıraya gireceğini belirler.
         */
        olcut: 'yatirimGetirisi' | 'yeniEklenenler' | 'gizliPortfoy' | 'ticariSanayi';
        aktif?: boolean | null;
        /**
         * Boş bırakılırsa ölçütün varsayılan başlığı kullanılır. ⚠️ Emoji kullanma; başlık ölçüt söylemeli.
         */
        baslik?: string | null;
        /**
         * Ziyaretçiye "neye göre bu sırada?" sorusunun cevabını verir. Boş bırakılırsa varsayılan açıklama kullanılır.
         */
        altBaslik?: string | null;
        /**
         * Yatay sıra kaydırmalıdır; 8–12 arası hem doyurucu hem hızlı kalır.
         */
        adet?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Sayfanın davet metni. Sayfanın açık/kapalı olması Ayarlar → Site Bölümleri altında.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danisman-ol".
 */
export interface DanismanOl {
  id: number;
  /**
   * Boşsa varsayılan başlık kullanılır.
   */
  baslik?: string | null;
  /**
   * Davet bloğunda başlığın altında görünür.
   */
  aciklama?: string | null;
  /**
   * ⚠️ Kazanç vaadi ya da garanti içeren ifade yazma — reklam mevzuatı açısından risklidir. Somut ve doğrulanabilir maddeler kullan.
   */
  nedenler?:
    | {
        baslik: string;
        metin?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Değerleme modelinin katsayıları. Girilmeyen katsayı hesaba katılmaz — tahmini bir değer uydurulmaz. Katsayılar çarpımsaldır: 1,00 etkisiz demektir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "degerleme-ayarlari".
 */
export interface DegerlemeAyarlari {
  id: number;
  /**
   * Örnek düşünce: zemin kat genellikle ara kattan düşük, yüksek kat manzara varsa yüksek değerlenir. Rakamları kendi gözleminize göre siz belirleyin.
   */
  katKatsayilari?:
    | {
        kat: 'bodrum' | 'zemin' | 'ara' | 'yuksek' | 'en_ust';
        /**
         * 1,00 = etkisiz
         */
        katsayi: number;
        id?: string | null;
      }[]
    | null;
  durumKatsayilari?:
    | {
        durum: 'sifir' | 'iyi' | 'ortalama' | 'tadilat';
        katsayi: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Her dilim için ÜST YAŞ sınırı ve katsayı girin. En yaşlı dilimin üst sınırını BOŞ bırakın ("ve üzeri"). Sıralama önemli değil, sistem kendisi sıralar.
   */
  yasKatsayilari?:
    | {
        /**
         * En yaşlı dilimde boş bırakın.
         */
        ustYas?: number | null;
        katsayi: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Katsayıları neye göre belirlediğinizi buraya yazın. Bir müşteri veya gazeteci "bu rakamı nasıl buldunuz?" diye sorduğunda cevabınız hazır olsun.
   */
  notlar?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Çorlu Konut Endeksi sepet ağırlıkları ve yayın durumu. Ağırlıklar yılda bir kez, Ocak ayında güncellenir.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endeks-ayarlari".
 */
export interface EndeksAyarlari {
  id: number;
  /**
   * ⚠️ Bu kutuyu işaretlemek TEK BAŞINA yeterli değildir. Sistem ayrıca veri koşullarını kontrol eder (en az 6 ay, 500 gözlem, %70 ağırlık kapsamı, metodoloji sayfası yayında). Koşullar sağlanmazsa sayfa 404 döner. Bu kontrol koda gömülüdür ve "bir ay erken açalım" cazibesine karşı durur.
   */
  yayinda?: boolean | null;
  /**
   * Endeks, metodolojisi yayınlanmadan yayına alınamaz. Yöntemi açıklamak hem güven hem koruma sağlar: "yöntemimiz açık, isteyen kontrol edebilir".
   */
  metodolojiYayinda?: boolean | null;
  /**
   * Her katman (mahalle × oda tipi) için ağırlık. Ağırlıklar KONUT STOKUNU temsil etmeli, gözlem sayınızı değil. Toplamı 1,00 olmalı. Başlangıçta saha bilginizle tahmin edin; TÜİK bina sayımı varsa iyileştirin.
   */
  sepetAgirliklari?:
    | {
        mahalle: number | Mahalleler;
        odaTipi: '1+1' | '2+1' | '3+1' | '4+1';
        /**
         * Örn: 0,14
         */
        agirlik: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Ağırlıkları en son hangi yıl gözden geçirdiniz?
   */
  agirlikGuncellemeYili?: number | null;
  /**
   * Üç ayda bir TCMB Tekirdağ konut fiyat endeksiyle karşılaştırın. Sapma %5'i geçerse veriyi gözden geçirin. Sonucu buraya not edin — kendinizi denetlemenin en ucuz yolu budur.
   */
  tcmbKarsilastirmaNotu?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bakım görevlerinin son çalışma bilgisi. Görevler otomatik yazar; elle değiştirmeyin.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bakim-durumu".
 */
export interface BakimDurumu {
  id: number;
  /**
   * Her satır bir bakım görevinin son durumunu tutar. Tanımlı görevler: eids-kaldir, eids-uyar, kvkk-sil
   */
  gorevler?:
    | {
        anahtar: string;
        sonCalisma?: string | null;
        sonBasariliCalisma?: string | null;
        sonHata?: string | null;
        sonIslenen?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Google Places API çağrılarının aylık sayısı. Yalnızca gerçekten yapılan çağrılar sayılır; sayaç elle düzenlenemez. Katmanı kapatmak için Site Bölümleri → "Google Places" anahtarını kullanın.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-places-kullanimi".
 */
export interface GooglePlacesKullanimi {
  id: number;
  aylar?:
    | {
        ay: string;
        aramaCagrisi?: number | null;
        detayCagrisi?: number | null;
        sonCagri?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kurumsal-bilgiler_select".
 */
export interface KurumsalBilgilerSelect<T extends boolean = true> {
  ticaretUnvani?: T;
  yetkiBelgesiNo?: T;
  mersisNo?: T;
  vergiDairesi?: T;
  vergiNo?: T;
  sorumluDanismanBelgeNo?: T;
  adres?: T;
  telefon?: T;
  eposta?: T;
  whatsapp?: T;
  calismaSaatleri?: T;
  sosyalMedya?:
    | T
    | {
        platform?: T;
        adres?: T;
        id?: T;
      };
  veriSorumlusu?: T;
  verbisKayitNo?: T;
  kvkkBasvuruEpostasi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hakkimizda_select".
 */
export interface HakkimizdaSelect<T extends boolean = true> {
  girisMetni?: T;
  icerik?: T;
  portre?: T;
  portreAltMetni?: T;
  ekGorseller?:
    | T
    | {
        gorsel?: T;
        aciklama?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-slider_select".
 */
export interface HeroSliderSelect<T extends boolean = true> {
  slaytlar?:
    | T
    | {
        gorsel?: T;
        baslik?: T;
        altBaslik?: T;
        butonMetni?: T;
        butonLink?: T;
        metinHizasi?: T;
        overlayKoyulugu?: T;
        aktif?: T;
        id?: T;
      };
  otomatikGecis?: T;
  gecisSuresi?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marka-gorunum_select".
 */
export interface MarkaGorunumSelect<T extends boolean = true> {
  siteAdi?: T;
  slogan?: T;
  logo?: T;
  logoKoyu?: T;
  simgeKaynak?: T;
  ogGorseli?: T;
  baslikEylemMetni?: T;
  baslikEylemAdresi?: T;
  acikTema?:
    | T
    | {
        zemin?: T;
        bolumZemin?: T;
        metin?: T;
        vurgu?: T;
        butonZemin?: T;
        butonMetin?: T;
        yumusakZemin?: T;
        dekoratifCizgi?: T;
        koyuBantZemin?: T;
        koyuBantMetin?: T;
      };
  koyuTema?:
    | T
    | {
        zemin?: T;
        bolumZemin?: T;
        metin?: T;
        vurgu?: T;
        butonZemin?: T;
        butonMetin?: T;
        yumusakZemin?: T;
        dekoratifCizgi?: T;
        koyuBantZemin?: T;
        koyuBantMetin?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-bolumleri_select".
 */
export interface SiteBolumleriSelect<T extends boolean = true> {
  danisman_ol?: T;
  harita?: T;
  ticari?: T;
  endeks?: T;
  raporlar?: T;
  gizli_portfoy?: T;
  mahalle_testi?: T;
  simulator?: T;
  ai_arama?: T;
  google_places?: T;
  bolge_radari?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "menu-duzeni_select".
 */
export interface MenuDuzeniSelect<T extends boolean = true> {
  sira?:
    | T
    | {
        oge?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfoy-bolumleri_select".
 */
export interface PortfoyBolumleriSelect<T extends boolean = true> {
  siralar?:
    | T
    | {
        olcut?: T;
        aktif?: T;
        baslik?: T;
        altBaslik?: T;
        adet?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "danisman-ol_select".
 */
export interface DanismanOlSelect<T extends boolean = true> {
  baslik?: T;
  aciklama?: T;
  nedenler?:
    | T
    | {
        baslik?: T;
        metin?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "degerleme-ayarlari_select".
 */
export interface DegerlemeAyarlariSelect<T extends boolean = true> {
  katKatsayilari?:
    | T
    | {
        kat?: T;
        katsayi?: T;
        id?: T;
      };
  durumKatsayilari?:
    | T
    | {
        durum?: T;
        katsayi?: T;
        id?: T;
      };
  yasKatsayilari?:
    | T
    | {
        ustYas?: T;
        katsayi?: T;
        id?: T;
      };
  notlar?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "endeks-ayarlari_select".
 */
export interface EndeksAyarlariSelect<T extends boolean = true> {
  yayinda?: T;
  metodolojiYayinda?: T;
  sepetAgirliklari?:
    | T
    | {
        mahalle?: T;
        odaTipi?: T;
        agirlik?: T;
        id?: T;
      };
  agirlikGuncellemeYili?: T;
  tcmbKarsilastirmaNotu?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "bakim-durumu_select".
 */
export interface BakimDurumuSelect<T extends boolean = true> {
  gorevler?:
    | T
    | {
        anahtar?: T;
        sonCalisma?: T;
        sonBasariliCalisma?: T;
        sonHata?: T;
        sonIslenen?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "google-places-kullanimi_select".
 */
export interface GooglePlacesKullanimiSelect<T extends boolean = true> {
  aylar?:
    | T
    | {
        ay?: T;
        aramaCagrisi?: T;
        detayCagrisi?: T;
        sonCagri?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}